# Generated by Django 4.2.13 on 2024-05-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1000, verbose_name="Наименование подразделения"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brief_description",
                    models.TextField(verbose_name="Краткое описание обнаружения"),
                ),
                (
                    "reccomendations",
                    models.TextField(
                        verbose_name="Рекоменлации подраздлеления внутреннего аудита"
                    ),
                ),
                (
                    "action_to_implement_the_recommendation",
                    models.TextField(
                        verbose_name="Мероприятие по исполнению рекомендации подразделения внутреннего аудита"
                    ),
                ),
                (
                    "form_of_completion",
                    models.CharField(max_length=250, verbose_name="Форма завершения"),
                ),
                ("deadline", models.DateTimeField(verbose_name="Срок исполнения")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Выполнено"),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, verbose_name="Выполнено не в установленный срок"
                    ),
                ),
                (
                    "not_done",
                    models.BooleanField(default=False, verbose_name="Не выполнено"),
                ),
                (
                    "removed_from_control",
                    models.BooleanField(default=False, verbose_name="Снято с контроля"),
                ),
                (
                    "rescheduled",
                    models.BooleanField(default=False, verbose_name="Перенесено"),
                ),
                (
                    "departament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audit.department",
                        verbose_name="Наименование подразделения",
                    ),
                ),
            ],
        ),
    ]
